LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := AudioWizardView
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := AudioWizardView/AudioWizardView.apk
LOCAL_OVERRIDES_PACKAGES := AudioFX
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := DtsUltra
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := DtsUltra/DtsUltra.apk
LOCAL_OVERRIDES_PACKAGES := AudioFX
include $(BUILD_PREBUILT)